import json
import os
os.environ['MPLCONFIGDIR'] = '/tmp/matplotlib'
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

def main():
    # Setup directories
    script_dir = os.path.dirname(os.path.abspath(__file__))
    archive_dir = os.path.dirname(script_dir)
    images_dir = os.path.join(archive_dir, 'images')
    os.makedirs(images_dir, exist_ok=True)

    # Paths to JSON data generated by the Rust sweep runner.
    artifacts_dir = os.path.join(archive_dir, 'artifacts')
    results_path = os.path.join(artifacts_dir, 'growth_v2_sweep_results.json')
    plot_data_path = os.path.join(artifacts_dir, 'growth_v2_sweep_plot_data.json')

    if not os.path.exists(results_path) or not os.path.exists(plot_data_path):
        print("Data files not found. Ensure the sweep test has run.")
        return

    with open(results_path) as f:
        results = json.load(f)

    with open(plot_data_path) as f:
        plot_data = json.load(f)

    somas = plot_data['somas']
    baseline_axons = plot_data['baseline_axons']
    winner_axons = plot_data['winner_axons']
    baseline_synapses = plot_data['baseline_synapses']
    winner_synapses = plot_data['winner_synapses']

    # Curated colors for neuron types:
    # 0: VirtualInput, 1: L4_spiny, 2: L23_aspiny, 3: L5_spiny
    type_colors = {
        0: '#3a86c8', # slate blue
        1: '#ff006e', # deep pink
        2: '#8338ec', # purple
        3: '#fb5607', # orange
        4: '#ffbe0b'  # gold (unused/fallback)
    }
    type_names = {
        0: 'VirtualInput',
        1: 'L4_spiny',
        2: 'L23_aspiny',
        3: 'L5_spiny',
        4: 'NoDendriteSource'
    }

    # ----------------------------------------------------
    # Plot 1: 3D Shard Overview (Config 16 somas + axons)
    # ----------------------------------------------------
    fig = plt.figure(figsize=(10, 8))
    ax = fig.add_subplot(111, projection='3d')
    ax.set_facecolor('#ffffff')

    # Plot somas
    soma_x = [s['x'] for s in somas]
    soma_y = [s['y'] for s in somas]
    soma_z = [s['z'] for s in somas]
    soma_col = [type_colors.get(s['variant_id'], '#888888') for s in somas]
    ax.scatter(soma_x, soma_y, soma_z, c=soma_col, s=25, alpha=0.6, edgecolors='none', label='Somas')

    # Plot first 20 axons of Config 16.
    axons_plotted = 0
    for axon in winner_axons:
        if axons_plotted >= 20:
            break
        # Draw all branches of the axon
        for b_idx, branch in enumerate(axon['branches']):
            if not branch:
                continue
            bx = [p[0] for p in branch]
            by = [p[1] for p in branch]
            bz = [p[2] for p in branch]
            # Use distinct line style for branches vs stem
            color = '#4a4e69' if b_idx == 0 else '#ff006e'
            alpha = 0.8 if b_idx == 0 else 0.9
            width = 1.5 if b_idx == 0 else 1.0
            ax.plot(bx, by, bz, color=color, alpha=alpha, linewidth=width)
        axons_plotted += 1

    ax.set_title('3D Shard Overview: Config 16 Compile Candidate\n(Branching highlighted in magenta, main stem in grey)', fontsize=12, fontweight='bold')
    ax.set_xlabel('Width (X) um')
    ax.set_ylabel('Depth (Y) um')
    ax.set_zlabel('Height (Z) um')
    ax.view_init(elev=20, azim=45)
    plt.tight_layout()
    plt.savefig(os.path.join(images_dir, '3d_shard_overview.png'), dpi=150)
    plt.close()
    print("Wrote 3d_shard_overview.png")

    # ----------------------------------------------------
    # Plot 2: 3D Accepted Synapses / Touch Points
    # ----------------------------------------------------
    fig = plt.figure(figsize=(10, 8))
    ax = fig.add_subplot(111, projection='3d')
    ax.set_facecolor('#ffffff')

    syn_x = [s['x'] for s in winner_synapses]
    syn_y = [s['y'] for s in winner_synapses]
    syn_z = [s['z'] for s in winner_synapses]
    # Color by target type
    syn_col = [type_colors.get(s['target_variant'], '#888888') for s in winner_synapses]
    
    scatter = ax.scatter(syn_x, syn_y, syn_z, c=syn_col, s=20, alpha=0.8, edgecolors='none')
    
    ax.set_title('3D Accepted Synapses (Config 16 Compile Candidate)\n(Color represents target neuron type)', fontsize=12, fontweight='bold')
    ax.set_xlabel('X um')
    ax.set_ylabel('Y um')
    ax.set_zlabel('Z um')
    ax.view_init(elev=15, azim=60)
    plt.tight_layout()
    plt.savefig(os.path.join(images_dir, '3d_touch_points.png'), dpi=150)
    plt.close()
    print("Wrote 3d_touch_points.png")

    # ----------------------------------------------------
    # Plot 3: Per-Layer Projection Heatmap
    # ----------------------------------------------------
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))
    
    # Layer order
    layers = ['VirtualInput', 'L4_spiny', 'L23_aspiny', 'L5_spiny']
    
    for ax_idx, (syns, title) in enumerate([(baseline_synapses, 'Baseline (Multifield v0.2)'), 
                                            (winner_synapses, 'Config 16 Compile Candidate')]):
        matrix = np.zeros((len(layers), len(layers)))
        for s in syns:
            src_name = type_names.get(s['source_variant'], '')
            tgt_name = type_names.get(s['target_variant'], '')
            if src_name in layers and tgt_name in layers:
                src_i = layers.index(src_name)
                tgt_i = layers.index(tgt_name)
                matrix[src_i, tgt_i] += 1
        
        im = axes[ax_idx].imshow(matrix, cmap='YlOrRd', aspect='equal')
        axes[ax_idx].set_title(title, fontsize=11, fontweight='bold')
        axes[ax_idx].set_xticks(range(len(layers)))
        axes[ax_idx].set_yticks(range(len(layers)))
        axes[ax_idx].set_xticklabels(layers, rotation=15, ha='right')
        axes[ax_idx].set_yticklabels(layers)
        axes[ax_idx].set_xlabel('Target Layer/Type')
        axes[ax_idx].set_ylabel('Source Layer/Type')
        
        # Annotate matrix
        for i in range(len(layers)):
            for j in range(len(layers)):
                axes[ax_idx].text(j, i, f"{int(matrix[i, j])}",
                                  ha="center", va="center", color="black" if matrix[i, j] < matrix.max()/2 else "white")
                
    fig.suptitle('Synaptic Projections Matrix (Source vs Target counts)', fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.savefig(os.path.join(images_dir, 'projection_heatmap.png'), dpi=150)
    plt.close()
    print("Wrote projection_heatmap.png")

    # ----------------------------------------------------
    # Plot 4: Target Fan-In Distribution (Histogram)
    # ----------------------------------------------------
    fig, ax = plt.subplots(figsize=(8, 5))
    
    # Calculate fan-in
    def get_fan_in(syns, num_somas):
        counts = [0] * num_somas
        for s in syns:
            counts[s['target']] += 1
        return counts

    num_somas = len(somas)
    baseline_fan_in = get_fan_in(baseline_synapses, num_somas)
    winner_fan_in = get_fan_in(winner_synapses, num_somas)

    ax.hist(baseline_fan_in, bins=30, alpha=0.6, label='Baseline (Multifield v0.2)', color='#3a86c8')
    ax.hist(winner_fan_in, bins=30, alpha=0.7, label='Config 16 Compile Candidate', color='#ff006e')
    ax.set_title('Target Fan-In Synaptic Density Distribution', fontsize=12, fontweight='bold')
    ax.set_xlabel('Synapse Count per Target Soma (Fan-In)')
    ax.set_ylabel('Neuron Count')
    ax.legend()
    plt.tight_layout()
    plt.savefig(os.path.join(images_dir, 'fan_in_histogram.png'), dpi=150)
    plt.close()
    print("Wrote fan_in_histogram.png")

    # ----------------------------------------------------
    # Plot 5: Raw vs Accepted vs Pruned Bar Chart per Config
    # ----------------------------------------------------
    fig, ax = plt.subplots(figsize=(14, 6))
    
    names = [r['config_name'].split('. ')[1] for r in results]
    raw_cands = [r['raw_candidate_count'] for r in results]
    accepted = [r['accepted_synapse_count'] for r in results]
    uniq_pruned = [r['uniqueness_pruned_count'] for r in results]
    cap_pruned = [r['dropped_candidate_count'] for r in results]
    
    x = np.arange(len(results))
    width = 0.22
    
    rects1 = ax.bar(x - 1.5*width, raw_cands, width, label='Raw Candidates', color='#8338ec', alpha=0.7)
    rects2 = ax.bar(x - 0.5*width, uniq_pruned, width, label='Uniqueness Pruned', color='#ffbe0b', alpha=0.8)
    rects3 = ax.bar(x + 0.5*width, cap_pruned, width, label='Cap Pruned (128)', color='#ff006e', alpha=0.8)
    rects4 = ax.bar(x + 1.5*width, accepted, width, label='Accepted Synapses', color='#3a86c8', alpha=0.9)
    
    ax.set_title('Synaptogenesis Pruning & Capping Volume Across 16 Sweep Configurations', fontsize=14, fontweight='bold')
    ax.set_ylabel('Counts')
    ax.set_xticks(x)
    ax.set_xticklabels(names, rotation=35, ha='right')
    ax.legend()
    ax.set_yscale('log') # Use log scale because baseline has ~190k cands and overridden has ~1k
    plt.tight_layout()
    plt.savefig(os.path.join(images_dir, 'pruning_breakdown.png'), dpi=150)
    plt.close()
    print("Wrote pruning_breakdown.png")

    # ----------------------------------------------------
    # Plot 6: TKI / Branch Spread Scatter
    # ----------------------------------------------------
    fig, ax = plt.subplots(figsize=(8, 5))
    
    tkis = [r['mean_terminal_knot_index'] for r in results]
    spreads = [r['mean_arbor_spread_radius'] for r in results]
    config_labels = [r['config_name'].split('. ')[0] for r in results]
    
    scatter = ax.scatter(spreads, tkis, c=range(len(results)), cmap='tab20', s=100, alpha=0.8, edgecolors='black')
    
    for i, txt in enumerate(config_labels):
        ax.annotate(txt, (spreads[i] + 0.05, tkis[i]), fontsize=9)
        
    ax.set_title('Terminal Knot Index (TKI) vs Arbor Spread Radius', fontsize=12, fontweight='bold')
    ax.set_xlabel('Arbor Spread Radius (um)')
    ax.set_ylabel('Terminal Knot Index (TKI)')
    plt.tight_layout()
    plt.savefig(os.path.join(images_dir, 'tki_spread_scatter.png'), dpi=150)
    plt.close()
    print("Wrote tki_spread_scatter.png")

    # ----------------------------------------------------
    # Plot 7: Pareto Plot: success vs target saturation / raw pressure
    # ----------------------------------------------------
    fig, ax = plt.subplots(figsize=(8, 5))
    
    success_rates = [r['virtual_to_l4_success_rate'] * 100.0 for r in results]
    saturations = [r['saturated_target_somas_count'] for r in results]
    
    scatter = ax.scatter(success_rates, saturations, c=range(len(results)), cmap='tab20', s=100, alpha=0.8, edgecolors='black')
    
    for i, txt in enumerate(config_labels):
        ax.annotate(txt, (success_rates[i] + 0.5, saturations[i]), fontsize=9)
        
    ax.set_title('Pareto Frontier: Layer Success vs. Target Saturation (Max=256)', fontsize=12, fontweight='bold')
    ax.set_xlabel('Virtual -> L4 Projection Success Rate (%)')
    ax.set_ylabel('Saturated Target Neurons (Count)')
    plt.tight_layout()
    plt.savefig(os.path.join(images_dir, 'pareto_success_vs_pressure.png'), dpi=150)
    plt.close()
    print("Wrote pareto_success_vs_pressure.png")

if __name__ == '__main__':
    main()
