use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("generated");
    fs::create_dir_all(&dest_path).unwrap();
    let header_path = dest_path.join("axi_cuda_abi.h");

    // Rust values:
    let size_variant_parameters = std::mem::size_of::<layout::VariantParameters>();
    let align_variant_parameters = std::mem::align_of::<layout::VariantParameters>();

    let size_burst_heads = std::mem::size_of::<layout::BurstHeads8>();
    let align_burst_heads = std::mem::align_of::<layout::BurstHeads8>();

    let size_state_file_header = std::mem::size_of::<layout::StateFileHeader>();
    let align_state_file_header = std::mem::align_of::<layout::StateFileHeader>();

    let size_axons_file_header = std::mem::size_of::<layout::AxonsFileHeader>();
    let align_axons_file_header = std::mem::align_of::<layout::AxonsFileHeader>();

    let size_paths_file_header = std::mem::size_of::<layout::PathsFileHeader>();
    let align_paths_file_header = std::mem::align_of::<layout::PathsFileHeader>();

    let size_shard_vram_ptrs = std::mem::size_of::<layout::ShardVramPtrs>();
    let align_shard_vram_ptrs = std::mem::align_of::<layout::ShardVramPtrs>();

    let cache_line_bytes = layout::CACHE_LINE_BYTES;
    let padded_n_alignment = layout::PADDED_N_ALIGNMENT;

    let axon_sentinel = types::AXON_SENTINEL;
    let empty_pixel = types::EMPTY_PIXEL;

    let min_weight_limit = physics::constants::MIN_WEIGHT_LIMIT;
    let max_weight_limit = physics::constants::MAX_WEIGHT_LIMIT;
    let dds_phase_mod = physics::constants::DDS_PHASE_MOD;
    let dds_phase_mask = physics::constants::DDS_PHASE_MASK;
    let dds_scatter_prime = physics::constants::DDS_SCATTER_PRIME;
    let max_heartbeat_m = physics::constants::MAX_HEARTBEAT_M;
    let variant_lut_len = layout::VARIANT_LUT_LEN;

    let max_dendrites = layout::MAX_DENDRITES;
    let max_axon_id = types::MAX_AXON_ID;
    let max_segment_offset = types::MAX_SEGMENT_OFFSET;
    let mass_to_charge_shift = physics::constants::MASS_TO_CHARGE_SHIFT;

    let dummy = layout::VariantParameters {
        threshold: 0,
        rest_potential: 0,
        leak_shift: 0,
        homeostasis_penalty: 0,
        spontaneous_firing_period_ticks: 0,
        initial_synapse_weight: 0,
        gsop_potentiation: 0,
        gsop_depression: 0,
        homeostasis_decay: 0,
        refractory_period: 0,
        synapse_refractory_period: 0,
        signal_propagation_length: 0,
        is_inhibitory: 0,
        inertia_curve: [0; 8],
        ahp_amplitude: 0,
        _pad1: [0; 6],
        adaptive_leak_min_shift: 0,
        adaptive_leak_gain: 0,
        adaptive_mode: 0,
        _leak_pad: [0; 3],
        d1_affinity: 0,
        d2_affinity: 0,
        heartbeat_m: 0,
    };
    let base_ptr = &dummy as *const _ as usize;
    let off_threshold = (&dummy.threshold as *const _ as usize) - base_ptr;
    let off_rest_potential = (&dummy.rest_potential as *const _ as usize) - base_ptr;
    let off_leak_shift = (&dummy.leak_shift as *const _ as usize) - base_ptr;
    let off_homeostasis_penalty = (&dummy.homeostasis_penalty as *const _ as usize) - base_ptr;
    let off_homeostasis_decay = (&dummy.homeostasis_decay as *const _ as usize) - base_ptr;
    let off_refractory_period = (&dummy.refractory_period as *const _ as usize) - base_ptr;
    let off_ahp_amplitude = (&dummy.ahp_amplitude as *const _ as usize) - base_ptr;
    let off_adaptive_leak_min_shift =
        (&dummy.adaptive_leak_min_shift as *const _ as usize) - base_ptr;
    let off_adaptive_leak_gain = (&dummy.adaptive_leak_gain as *const _ as usize) - base_ptr;
    let off_adaptive_mode = (&dummy.adaptive_mode as *const _ as usize) - base_ptr;
    let off_signal_propagation_length =
        (&dummy.signal_propagation_length as *const _ as usize) - base_ptr;
    let off_heartbeat_m = (&dummy.heartbeat_m as *const _ as usize) - base_ptr;
    let off_gsop_potentiation = (&dummy.gsop_potentiation as *const _ as usize) - base_ptr;
    let off_gsop_depression = (&dummy.gsop_depression as *const _ as usize) - base_ptr;
    let off_d1_affinity = (&dummy.d1_affinity as *const _ as usize) - base_ptr;
    let off_d2_affinity = (&dummy.d2_affinity as *const _ as usize) - base_ptr;
    let off_inertia_curve = (&dummy.inertia_curve as *const _ as usize) - base_ptr;

    let inertia_rank_shift = physics::constants::INERTIA_RANK_SHIFT;
    let max_inertia_rank = physics::constants::MAX_INERTIA_RANK;

    let soma_spiking_mask = types::SOMA_SPIKING_MASK;
    let soma_burst_mask = types::SOMA_BURST_MASK;
    let soma_burst_shift = types::SOMA_BURST_SHIFT;
    let soma_type_mask = types::SOMA_TYPE_MASK;
    let soma_type_shift = types::SOMA_TYPE_SHIFT;

    let content = format!(
        r#"/* Generated by compute-cuda build.rs. Do not edit. */
#ifndef AXI_CUDA_ABI_H
#define AXI_CUDA_ABI_H

/* Structure Sizes and Alignments */
#define AXI_SIZE_VariantParameters {size_variant_parameters}
#define AXI_ALIGN_VariantParameters {align_variant_parameters}

#define AXI_SIZE_BurstHeads8 {size_burst_heads}
#define AXI_ALIGN_BurstHeads8 {align_burst_heads}

#define AXI_SIZE_StateFileHeader {size_state_file_header}
#define AXI_ALIGN_StateFileHeader {align_state_file_header}

#define AXI_SIZE_AxonsFileHeader {size_axons_file_header}
#define AXI_ALIGN_AxonsFileHeader {align_axons_file_header}

#define AXI_SIZE_PathsFileHeader {size_paths_file_header}
#define AXI_ALIGN_PathsFileHeader {align_paths_file_header}

#define AXI_SIZE_ShardVramPtrs {size_shard_vram_ptrs}
#define AXI_ALIGN_ShardVramPtrs {align_shard_vram_ptrs}

/* Layout Constants */
#define AXI_CACHE_LINE_BYTES {cache_line_bytes}
#define AXI_PADDED_N_ALIGNMENT {padded_n_alignment}
#define AXI_VARIANT_LUT_LEN {variant_lut_len}
#define AXI_MAX_DENDRITES {max_dendrites}

/* Types and Physics Constants */
#define AXI_AXON_SENTINEL 0x{axon_sentinel:08X}
#define AXI_EMPTY_PIXEL 0x{empty_pixel:08X}
#define AXI_MIN_WEIGHT_LIMIT {min_weight_limit}
#define AXI_MAX_WEIGHT_LIMIT {max_weight_limit}
#define AXI_DDS_PHASE_MOD {dds_phase_mod}ULL
#define AXI_DDS_PHASE_MASK 0x{dds_phase_mask:X}ULL
#define AXI_DDS_SCATTER_PRIME {dds_scatter_prime}ULL
#define AXI_MAX_HEARTBEAT_M {max_heartbeat_m}
#define AXI_MAX_AXON_ID {max_axon_id}
#define AXI_MAX_SEGMENT_OFFSET {max_segment_offset}
#define AXI_MASS_TO_CHARGE_SHIFT {mass_to_charge_shift}
#define AXI_INERTIA_RANK_SHIFT {inertia_rank_shift}
#define AXI_MAX_INERTIA_RANK {max_inertia_rank}

/* SomaFlags Masks and Shifts */
#define AXI_SOMA_SPIKING_MASK {soma_spiking_mask}
#define AXI_SOMA_BURST_MASK {soma_burst_mask}
#define AXI_SOMA_BURST_SHIFT {soma_burst_shift}
#define AXI_SOMA_TYPE_MASK {soma_type_mask}
#define AXI_SOMA_TYPE_SHIFT {soma_type_shift}

/* VariantParameters Offsets */
#define AXI_OFFSET_VariantParameters_threshold {off_threshold}
#define AXI_OFFSET_VariantParameters_rest_potential {off_rest_potential}
#define AXI_OFFSET_VariantParameters_leak_shift {off_leak_shift}
#define AXI_OFFSET_VariantParameters_homeostasis_penalty {off_homeostasis_penalty}
#define AXI_OFFSET_VariantParameters_homeostasis_decay {off_homeostasis_decay}
#define AXI_OFFSET_VariantParameters_refractory_period {off_refractory_period}
#define AXI_OFFSET_VariantParameters_ahp_amplitude {off_ahp_amplitude}
#define AXI_OFFSET_VariantParameters_adaptive_leak_min_shift {off_adaptive_leak_min_shift}
#define AXI_OFFSET_VariantParameters_adaptive_leak_gain {off_adaptive_leak_gain}
#define AXI_OFFSET_VariantParameters_adaptive_mode {off_adaptive_mode}
#define AXI_OFFSET_VariantParameters_signal_propagation_length {off_signal_propagation_length}
#define AXI_OFFSET_VariantParameters_heartbeat_m {off_heartbeat_m}
#define AXI_OFFSET_VariantParameters_gsop_potentiation {off_gsop_potentiation}
#define AXI_OFFSET_VariantParameters_gsop_depression {off_gsop_depression}
#define AXI_OFFSET_VariantParameters_d1_affinity {off_d1_affinity}
#define AXI_OFFSET_VariantParameters_d2_affinity {off_d2_affinity}
#define AXI_OFFSET_VariantParameters_inertia_curve {off_inertia_curve}

#endif /* AXI_CUDA_ABI_H */
"#
    );

    fs::write(&header_path, content).unwrap();

    #[cfg(feature = "native")]
    {
        cc::Build::new()
            .cuda(true)
            .include(&dest_path)
            .file("src/kernels/scalar_golden.cu")
            .compile("axi_cuda_kernels");

        println!("cargo:rustc-link-lib=dylib=cudart");
        println!("cargo:rerun-if-changed=src/kernels/scalar_golden.cu");
        println!("cargo:rerun-if-changed=src/kernels/");
    }

    // Re-run triggers
    println!("cargo:rerun-if-changed=build.rs");
}
