use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("generated");
    fs::create_dir_all(&dest_path).unwrap();
    let header_path = dest_path.join("axi_cuda_abi.h");

    // Rust values:
    let size_variant_parameters = std::mem::size_of::<layout::VariantParameters>();
    let align_variant_parameters = std::mem::align_of::<layout::VariantParameters>();

    let size_burst_heads = std::mem::size_of::<layout::BurstHeads8>();
    let align_burst_heads = std::mem::align_of::<layout::BurstHeads8>();

    let size_state_file_header = std::mem::size_of::<layout::StateFileHeader>();
    let align_state_file_header = std::mem::align_of::<layout::StateFileHeader>();

    let size_axons_file_header = std::mem::size_of::<layout::AxonsFileHeader>();
    let align_axons_file_header = std::mem::align_of::<layout::AxonsFileHeader>();

    let size_paths_file_header = std::mem::size_of::<layout::PathsFileHeader>();
    let align_paths_file_header = std::mem::align_of::<layout::PathsFileHeader>();

    let size_shard_vram_ptrs = std::mem::size_of::<layout::ShardVramPtrs>();
    let align_shard_vram_ptrs = std::mem::align_of::<layout::ShardVramPtrs>();

    let cache_line_bytes = layout::CACHE_LINE_BYTES;
    let padded_n_alignment = layout::PADDED_N_ALIGNMENT;

    let axon_sentinel = types::AXON_SENTINEL;
    let empty_pixel = types::EMPTY_PIXEL;

    let min_weight_limit = physics::constants::MIN_WEIGHT_LIMIT;
    let max_weight_limit = physics::constants::MAX_WEIGHT_LIMIT;
    let dds_phase_mod = physics::constants::DDS_PHASE_MOD;
    let dds_phase_mask = physics::constants::DDS_PHASE_MASK;
    let dds_scatter_prime = physics::constants::DDS_SCATTER_PRIME;
    let max_heartbeat_m = physics::constants::MAX_HEARTBEAT_M;
    let variant_lut_len = layout::VARIANT_LUT_LEN;

    let content = format!(
        r#"/* Generated by compute-cuda build.rs. Do not edit. */
#ifndef AXI_CUDA_ABI_H
#define AXI_CUDA_ABI_H

/* Structure Sizes and Alignments */
#define AXI_SIZE_VariantParameters {size_variant_parameters}
#define AXI_ALIGN_VariantParameters {align_variant_parameters}

#define AXI_SIZE_BurstHeads8 {size_burst_heads}
#define AXI_ALIGN_BurstHeads8 {align_burst_heads}

#define AXI_SIZE_StateFileHeader {size_state_file_header}
#define AXI_ALIGN_StateFileHeader {align_state_file_header}

#define AXI_SIZE_AxonsFileHeader {size_axons_file_header}
#define AXI_ALIGN_AxonsFileHeader {align_axons_file_header}

#define AXI_SIZE_PathsFileHeader {size_paths_file_header}
#define AXI_ALIGN_PathsFileHeader {align_paths_file_header}

#define AXI_SIZE_ShardVramPtrs {size_shard_vram_ptrs}
#define AXI_ALIGN_ShardVramPtrs {align_shard_vram_ptrs}

/* Layout Constants */
#define AXI_CACHE_LINE_BYTES {cache_line_bytes}
#define AXI_PADDED_N_ALIGNMENT {padded_n_alignment}
#define AXI_VARIANT_LUT_LEN {variant_lut_len}

/* Types and Physics Constants */
#define AXI_AXON_SENTINEL 0x{axon_sentinel:08X}
#define AXI_EMPTY_PIXEL 0x{empty_pixel:08X}
#define AXI_MIN_WEIGHT_LIMIT {min_weight_limit}
#define AXI_MAX_WEIGHT_LIMIT {max_weight_limit}
#define AXI_DDS_PHASE_MOD {dds_phase_mod}ULL
#define AXI_DDS_PHASE_MASK 0x{dds_phase_mask:X}ULL
#define AXI_DDS_SCATTER_PRIME {dds_scatter_prime}ULL
#define AXI_MAX_HEARTBEAT_M {max_heartbeat_m}

#endif /* AXI_CUDA_ABI_H */
"#
    );

    fs::write(&header_path, content).unwrap();

    #[cfg(feature = "native")]
    {
        cc::Build::new()
            .cuda(true)
            .include(&dest_path)
            .file("src/kernels/scalar_golden.cu")
            .compile("axi_cuda_kernels");

        println!("cargo:rustc-link-lib=dylib=cudart");
        println!("cargo:rerun-if-changed=src/kernels/scalar_golden.cu");
        println!("cargo:rerun-if-changed=src/kernels/");
    }

    // Re-run triggers
    println!("cargo:rerun-if-changed=build.rs");
}
